"""Your message about this migration

Revision ID: 1635675e721c
Revises: cb4199c28db7
Create Date: 2024-01-04 21:17:55.315948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1635675e721c'
down_revision = 'cb4199c28db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streckenhalteplan')
    op.drop_table('fahrtdurchführung')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fahrtdurchführung',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('datum', sa.DATE(), nullable=False),
    sa.Column('zeit', sa.TIME(), nullable=True),
    sa.Column('endzeit', sa.TIME(), nullable=True),
    sa.Column('zug_id', sa.INTEGER(), nullable=True),
    sa.Column('line', sa.INTEGER(), nullable=True),
    sa.Column('mitarbeiter_ids', sa.VARCHAR(), nullable=True),
    sa.Column('preise', sa.VARCHAR(), nullable=True),
    sa.Column('bahnhof_ids', sa.VARCHAR(), nullable=True),
    sa.Column('zeiten', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streckenhalteplan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('start_station_id', sa.INTEGER(), nullable=True),
    sa.Column('end_station_id', sa.INTEGER(), nullable=True),
    sa.Column('original_line_id', sa.INTEGER(), nullable=True),
    sa.Column('travel_duration', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
