"""New trainstaton

Revision ID: 6831e5f38ee3
Revises: b9593100ef06
Create Date: 2024-01-07 21:00:04.976496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6831e5f38ee3'
down_revision = 'b9593100ef06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_station_id', sa.Integer(), nullable=True),
    sa.Column('end_station_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['end_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['start_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    op.drop_table('journeys')
    # ### end Alembic commands ###
