"""Added all_lines field to Sale model

Revision ID: 6ce32c216837
Revises: 87f6a8df5349
Create Date: 2024-01-18 12:35:13.747728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce32c216837'
down_revision = '87f6a8df5349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_lines', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('all_lines')

    # ### end Alembic commands ###
