"""Your message about this migration

Revision ID: b729b621efc6
Revises: 1635675e721c
Create Date: 2024-01-04 22:37:40.586661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b729b621efc6'
down_revision = '1635675e721c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
