"""Your message

Revision ID: e318d50eea2f
Revises: e0e3e752b34d
Create Date: 2024-01-16 16:54:41.546676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e318d50eea2f'
down_revision = 'e0e3e752b34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_reserved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seat_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('seat_number')
        batch_op.drop_column('seat_reserved')

    # ### end Alembic commands ###
