"""maintenance

Revision ID: 09c0e7b03e21
Revises: f847e6319e3b
Create Date: 2023-11-24 08:57:18.364121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c0e7b03e21'
down_revision = 'f847e6319e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_user_association',
    sa.Column('maintenance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.drop_column('assigned_employees')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_employees', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('maintenance_user_association')
    # ### end Alembic commands ###
