"""train price per km

Revision ID: 0dd9a80a69bf
Revises: 2817c9307bce
Create Date: 2023-11-21 20:47:42.497375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd9a80a69bf'
down_revision = '2817c9307bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_km', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.drop_column('price_per_km')

    # ### end Alembic commands ###
