"""Wagons

Revision ID: ae641461a501
Revises: 754659cfae48
Create Date: 2023-11-19 14:08:41.496505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae641461a501'
down_revision = '754659cfae48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wagon', schema=None) as batch_op:
        batch_op.alter_column('max_traction',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('max_weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('number_of_seats',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wagon', schema=None) as batch_op:
        batch_op.alter_column('number_of_seats',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('max_traction',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
