"""empty message

Revision ID: 238dd3438d46
Revises: 
Create Date: 2023-11-16 09:01:07.880602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238dd3438d46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chosen_sections_for_new_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chosen_sections_for_new_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_column('order')

    # ### end Alembic commands ###
