"""empty message

Revision ID: 8c22ab8d0e76
Revises: 238dd3438d46
Create Date: 2023-11-16 19:39:51.964749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c22ab8d0e76'
down_revision = '238dd3438d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('line_sections', schema=None) as batch_op:
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('startStation',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('endStation',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('endStation',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('startStation',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('line_sections', schema=None) as batch_op:
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
