"""Added Line model

Revision ID: b5a2544054fa
Revises: df02c1c12353
Create Date: 2023-11-08 19:41:05.216700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a2544054fa'
down_revision = 'df02c1c12353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameOfLine', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_sections',
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_sections')
    op.drop_table('line')
    # ### end Alembic commands ###
