"""Änderung.

Revision ID: da2c509065c7
Revises: f8f5e3a18d8b
Create Date: 2023-11-10 10:30:23.686806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2c509065c7'
down_revision = 'f8f5e3a18d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chosen_sections_for_new_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chosen_sections_for_new_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
