"""Added Event model

Revision ID: df02c1c12353
Revises: 7586aa9285e7
Create Date: 2023-11-07 21:41:29.044749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df02c1c12353'
down_revision = '7586aa9285e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('officialText', sa.String(length=200), nullable=True),
    sa.Column('internalText', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['section'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
